services:
    api:
        build: .
        container_name: adidas-challenge-subscription-service
        depends_on:
            - mongo
        ports:
            - "3001:3001"
        environment:
            MONGODB_URI: mongodb://mongo:27017
            EMAIL_SERVICE_URL: http://adidas-challenge-email-service:3002/emails
        networks:
            - adidas_challenge

    mongo:
        image: mongo
        restart: always
        container_name: mongo_adidas
        environment:
            MONGO_INITDB_DATABASE: adidas
            MONGO_INITDB_ROOT_USERNAME: adidas
            MONGO_INITDB_ROOT_PASSWORD: adidas
        ports:
            - "27017:27017"
        networks:
            - adidas_challenge

networks:
    adidas_challenge:
        name: adidas_challenge
